// ═══════════════════════════════════════════════════════
// EXECUTION OS — Rich Mock Data v3.0
// All dates relative to TODAY = 2026-02-17
// ═══════════════════════════════════════════════════════

import type {
  Project, Sprint, TaskList, Milestone, Task, SubTask,
  Issue, TeamMember, TimeLog, TaskDependency, SkillRating, EmailThread
} from './workTypes';

// ─── Projects (updated to 2026) ──────────────────────────
export const mockProjects: Project[] = [
  {
    id: 'p1', name: 'Mobile App Redesign', code: 'MAR',
    client: 'TechCorp Inc', department: 'Product',
    status: 'Active', priority: 'High',
    startDate: '2025-12-01', endDate: '2026-04-30',
    progress: 48, budget: 120000, spent: 57600, burnRate: 88,
    profitRisk: 'Low', color: '#3b82f6',
    team: ['Sarah Chen', 'Mike Johnson', 'Emily Rodriguez', 'Alex Martinez'],
    teamLead: 'Sarah Chen',
    description: 'Complete redesign of mobile application with new UX patterns and improved accessibility',
    billingModel: 'Fixed', billableDefault: true, currency: 'USD',
    projectedMargin: 28, billableHours: 420, nonBillableHours: 85,
    taskCount: 67, openTaskCount: 34, milestoneCount: 4, openIssueCount: 7, sprintCount: 4,
  },
  {
    id: 'p2', name: 'E-commerce Platform', code: 'ECP',
    client: 'RetailCo', department: 'Engineering',
    status: 'At Risk', priority: 'High',
    startDate: '2025-11-15', endDate: '2026-03-31',
    progress: 42, budget: 200000, spent: 152000, burnRate: 124,
    profitRisk: 'High', color: '#ef4444',
    team: ['David Kim', 'Lisa Wang', 'James Taylor'],
    teamLead: 'David Kim',
    description: 'Full-stack e-commerce platform with payment integration and inventory management',
    billingModel: 'Hourly', billableDefault: true,
    taskCount: 84, openTaskCount: 52, milestoneCount: 5, openIssueCount: 18, sprintCount: 6,
  },
  {
    id: 'p3', name: 'Website Redesign', code: 'WRD',
    client: 'StartupXYZ', department: 'Design',
    status: 'Active', priority: 'Medium',
    startDate: '2026-01-05', endDate: '2026-05-20',
    progress: 28, budget: 75000, spent: 21000, burnRate: 65,
    profitRisk: 'Low', color: '#10b981',
    team: ['Emma Wilson', 'Alex Martinez'],
    teamLead: 'Emma Wilson',
    description: 'Modern website redesign with improved accessibility and performance',
    billingModel: 'Fixed', billableDefault: true,
    taskCount: 38, openTaskCount: 30, milestoneCount: 3, openIssueCount: 4, sprintCount: 2,
  },
  {
    id: 'p4', name: 'Platform API v3', code: 'PAV',
    client: 'Internal', department: 'Engineering',
    status: 'Active', priority: 'Medium',
    startDate: '2025-12-10', endDate: '2026-06-30',
    progress: 56, budget: 150000, spent: 84000, burnRate: 75,
    profitRisk: 'Medium', color: '#8b5cf6',
    team: ['Michael Brown', 'Sophie Anderson', 'Chris Lee'],
    teamLead: 'Michael Brown',
    description: 'RESTful API v3 with GraphQL support and improved rate limiting',
    billingModel: 'Retainer',
    taskCount: 54, openTaskCount: 24, milestoneCount: 3, openIssueCount: 9, sprintCount: 3,
  },
  {
    id: 'p5', name: 'Backend Infrastructure', code: 'BIN',
    client: 'Internal', department: 'Operations',
    status: 'Active', priority: 'Low',
    startDate: '2025-11-01', endDate: '2026-07-15',
    progress: 67, budget: 100000, spent: 67000, burnRate: 70,
    profitRisk: 'None', color: '#f59e0b',
    team: ['Chris Johnson', 'Maria Garcia'],
    teamLead: 'Chris Johnson',
    description: 'Infrastructure modernization: Kubernetes migration and observability stack',
    billingModel: 'Fixed',
    taskCount: 42, openTaskCount: 14, milestoneCount: 2, openIssueCount: 3, sprintCount: 2,
  },
  {
    id: 'p6', name: 'AI Analytics Dashboard', code: 'AAD',
    client: 'DataCo', department: 'Product',
    status: 'On Hold', priority: 'High',
    startDate: '2026-03-01', endDate: '2026-09-30',
    progress: 0, budget: 180000, spent: 0, burnRate: 0,
    profitRisk: 'Low', color: '#06b6d4',
    team: ['Sarah Chen', 'Michael Brown'],
    teamLead: 'Sarah Chen',
    description: 'Real-time AI analytics dashboard with predictive insights',
    billingModel: 'Fixed', billableDefault: true,
    taskCount: 0, openTaskCount: 0, milestoneCount: 4, openIssueCount: 0, sprintCount: 0,
  },
];

// ─── Sprints (2026 dates) ─────────────────────────────────
export const mockSprints: Sprint[] = [
  {
    id: 's1', name: 'Sprint 4 — UX Polish', projectId: 'p1', projectName: 'Mobile App Redesign',
    status: 'Active', startDate: '2026-02-10', endDate: '2026-02-24',
    goal: 'Complete all remaining UI components and fix accessibility issues',
    storyPoints: 42, completedPoints: 24, taskCount: 14, completedTasks: 8,
  },
  {
    id: 's2', name: 'Sprint 3 — Core Features', projectId: 'p1', projectName: 'Mobile App Redesign',
    status: 'Completed', startDate: '2026-01-27', endDate: '2026-02-09',
    goal: 'Deliver navigation system and onboarding flow',
    storyPoints: 38, completedPoints: 36, taskCount: 12, completedTasks: 11,
  },
  {
    id: 's3', name: 'Sprint 5 — Payments', projectId: 'p2', projectName: 'E-commerce Platform',
    status: 'Active', startDate: '2026-02-03', endDate: '2026-02-17',
    goal: 'Complete Stripe integration, checkout flow, and refund management',
    storyPoints: 55, completedPoints: 38, taskCount: 18, completedTasks: 12,
  },
  {
    id: 's4', name: 'Sprint 6 — Launch Prep', projectId: 'p2', projectName: 'E-commerce Platform',
    status: 'Planning', startDate: '2026-02-18', endDate: '2026-03-03',
    goal: 'Final bug fixes, performance optimization, and staging deployment',
    storyPoints: 48, completedPoints: 0, taskCount: 0, completedTasks: 0,
  },
  {
    id: 's5', name: 'Sprint 2 — API Core', projectId: 'p4', projectName: 'Platform API v3',
    status: 'Active', startDate: '2026-02-05', endDate: '2026-02-19',
    goal: 'Complete CRUD endpoints and authentication middleware',
    storyPoints: 60, completedPoints: 44, taskCount: 20, completedTasks: 14,
  },
  {
    id: 's6', name: 'Sprint 1 — Foundation', projectId: 'p3', projectName: 'Website Redesign',
    status: 'Completed', startDate: '2026-01-05', endDate: '2026-01-30',
    goal: 'Design system, brand colors, and information architecture',
    storyPoints: 32, completedPoints: 32, taskCount: 10, completedTasks: 10,
  },
];

// ─── Task Lists ───────────────────────────────────────────
export const mockTaskLists: TaskList[] = [
  { id: 'tl1', name: 'UI Components',    projectId: 'p1', sprintId: 's1', milestoneId: 'm3', status: 'Active',    taskCount: 8,  completedTasks: 4, order: 1 },
  { id: 'tl2', name: 'Navigation Flow',  projectId: 'p1', sprintId: 's1',                   status: 'Active',    taskCount: 6,  completedTasks: 4, order: 2 },
  { id: 'tl3', name: 'Checkout Module',  projectId: 'p2', sprintId: 's3', milestoneId: 'm5', status: 'Active',    taskCount: 10, completedTasks: 5, order: 1 },
  { id: 'tl4', name: 'API Endpoints',    projectId: 'p4', sprintId: 's5', milestoneId: 'm7', status: 'Active',    taskCount: 12, completedTasks: 9, order: 1 },
  { id: 'tl5', name: 'Design Research',  projectId: 'p3',                 milestoneId: 'm6', status: 'Completed', taskCount: 6,  completedTasks: 6, order: 1 },
  { id: 'tl6', name: 'Visual Mockups',   projectId: 'p3',                 milestoneId: 'm6', status: 'Active',    taskCount: 8,  completedTasks: 2, order: 2 },
];

// ─── Milestones (2026 dates) ──────────────────────────────
export const mockMilestones: Milestone[] = [
  {
    id: 'm1', projectId: 'p1', projectName: 'Mobile App Redesign',
    name: 'Phase 1: Discovery & Research', owner: 'Sarah Chen',
    startDate: '2025-12-01', endDate: '2025-12-20',
    progress: 100, status: 'Completed', taskCount: 8, completedTasks: 8,
  },
  {
    id: 'm2', projectId: 'p1', projectName: 'Mobile App Redesign',
    name: 'Phase 2: Design System', owner: 'Sarah Chen',
    startDate: '2025-12-21', endDate: '2026-01-15',
    progress: 100, status: 'Completed', taskCount: 12, completedTasks: 12,
  },
  {
    id: 'm3', projectId: 'p1', projectName: 'Mobile App Redesign',
    name: 'Phase 3: Core Development', owner: 'Mike Johnson',
    startDate: '2026-01-16', endDate: '2026-03-15',
    progress: 42, status: 'In Progress', taskCount: 24, completedTasks: 10,
  },
  {
    id: 'm4', projectId: 'p1', projectName: 'Mobile App Redesign',
    name: 'Phase 4: QA & Launch', owner: 'Sarah Chen',
    startDate: '2026-03-16', endDate: '2026-04-30',
    progress: 0, status: 'Not Started', taskCount: 18, completedTasks: 0,
  },
  {
    id: 'm5', projectId: 'p2', projectName: 'E-commerce Platform',
    name: 'Payment Integration', owner: 'Lisa Wang',
    startDate: '2026-01-01', endDate: '2026-02-10',
    progress: 62, status: 'Overdue', taskCount: 10, completedTasks: 6,
  },
  {
    id: 'm6', projectId: 'p3', projectName: 'Website Redesign',
    name: 'Visual Design Phase', owner: 'Emma Wilson',
    startDate: '2026-01-05', endDate: '2026-02-28',
    progress: 45, status: 'In Progress', taskCount: 14, completedTasks: 6,
  },
  {
    id: 'm7', projectId: 'p4', projectName: 'Platform API v3',
    name: 'Core Endpoints v3', owner: 'Michael Brown',
    startDate: '2025-12-10', endDate: '2026-02-28',
    progress: 78, status: 'In Progress', taskCount: 20, completedTasks: 16,
  },
  {
    id: 'm8', projectId: 'p5', projectName: 'Backend Infrastructure',
    name: 'Kubernetes Migration', owner: 'Chris Johnson',
    startDate: '2025-11-01', endDate: '2026-04-30',
    progress: 65, status: 'In Progress', taskCount: 22, completedTasks: 14,
  },
  {
    id: 'm9', projectId: 'p2', projectName: 'E-commerce Platform',
    name: 'Frontend UI Build', owner: 'David Kim',
    startDate: '2026-02-01', endDate: '2026-03-15',
    progress: 20, status: 'In Progress', taskCount: 16, completedTasks: 3,
  },
  {
    id: 'm10', projectId: 'p4', projectName: 'Platform API v3',
    name: 'GraphQL Layer', owner: 'Sophie Anderson',
    startDate: '2026-03-01', endDate: '2026-04-30',
    progress: 0, status: 'Not Started', taskCount: 12, completedTasks: 0,
  },
];

// ─── Subtasks ─────────────────────────────────────────────
const subtasksT1: SubTask[] = [
  { id: 'st1', title: 'Create login screen wireframe', status: 'Closed', priority: 'High', assignee: 'Sarah Chen', completed: true },
  { id: 'st2', title: 'Design password recovery flow', status: 'In Progress', priority: 'Medium', assignee: 'Sarah Chen', completed: false },
  { id: 'st3', title: 'Add biometric auth option', status: 'Open', priority: 'Low', assignee: 'Mike Johnson', completed: false },
];
const subtasksT3: SubTask[] = [
  { id: 'st4', title: 'Write endpoint specifications', status: 'Closed', priority: 'High', assignee: 'Michael Brown', completed: true },
  { id: 'st5', title: 'Add example responses', status: 'In Progress', priority: 'Medium', assignee: 'Sophie Anderson', completed: false },
];
const subtasksT8: SubTask[] = [
  { id: 'st6', title: 'Run OWASP security scan', status: 'Closed', priority: 'Critical', assignee: 'James Taylor', completed: true },
  { id: 'st7', title: 'Fix SQL injection vulnerabilities', status: 'In Progress', priority: 'Critical', assignee: 'James Taylor', completed: false },
  { id: 'st8', title: 'Update dependencies with CVEs', status: 'In Progress', priority: 'High', assignee: 'David Kim', completed: false },
  { id: 'st9', title: 'Generate security report', status: 'Open', priority: 'Medium', assignee: 'James Taylor', completed: false },
];
const subtasksT19: SubTask[] = [
  { id: 'st10', title: 'Setup Lottie animation library', status: 'Closed', priority: 'Medium', assignee: 'Sarah Chen', completed: true },
  { id: 'st11', title: 'Design step 1 animation', status: 'Closed', priority: 'High', assignee: 'Emily Rodriguez', completed: true },
  { id: 'st12', title: 'Design step 2 animation', status: 'In Progress', priority: 'High', assignee: 'Emily Rodriguez', completed: false },
  { id: 'st13', title: 'Implement progress indicator', status: 'Open', priority: 'Medium', assignee: 'Sarah Chen', completed: false },
];

// ─── TASKS — 35 entries covering all statuses ─────────────
export const mockTasks: Task[] = [
  // ── CLOSED (completed) ────────────────────────────────
  {
    id: 't4', taskId: 'WRD-007',
    title: 'Create landing page mockups',
    projectId: 'p3', projectName: 'Website Redesign', projectColor: '#10b981',
    milestoneId: 'm6', milestoneName: 'Visual Design Phase',
    taskListId: 'tl6', taskListName: 'Visual Mockups',
    assignee: 'Emma Wilson', assigneeDepartment: 'Design',
    status: 'Closed', priority: 'High',
    startDate: '2026-02-06', dueDate: '2026-02-15', completedDate: '2026-02-14',
    estimate: '12h', estimatedHours: 12, actualTime: '11h 30m', actualHours: 11.5,
    progress: 100, billable: true, hasEvidence: true, evidenceCount: 8,
    tags: ['design', 'mockup', 'landing'], comments: 7, attachments: 6, storyPoints: 5,
    burnAmount: 1150, profitImpact: 100, approvalStatus: 'Approved', client: 'StartupXYZ',
  },
  {
    id: 't6', taskId: 'BIN-019',
    title: 'PostgreSQL query optimization',
    projectId: 'p5', projectName: 'Backend Infrastructure', projectColor: '#f59e0b',
    milestoneId: 'm8', milestoneName: 'Kubernetes Migration',
    assignee: 'Chris Johnson', assigneeDepartment: 'Operations',
    status: 'Closed', priority: 'Low',
    startDate: '2026-02-03', dueDate: '2026-02-10', completedDate: '2026-02-09',
    estimate: '4h', estimatedHours: 4, actualTime: '4h 45m', actualHours: 4.75,
    progress: 100, billable: false, hasEvidence: true, evidenceCount: 2,
    tags: ['database', 'performance'], comments: 1, storyPoints: 2, burnAmount: 475,
    approvalStatus: 'Approved',
  },
  {
    id: 't14', taskId: 'WRD-015',
    title: 'Brand color system & design tokens',
    projectId: 'p3', projectName: 'Website Redesign', projectColor: '#10b981',
    milestoneId: 'm6', milestoneName: 'Visual Design Phase',
    taskListId: 'tl5', taskListName: 'Design Research',
    assignee: 'Emma Wilson', assigneeDepartment: 'Design',
    status: 'Closed', priority: 'High',
    startDate: '2026-01-10', dueDate: '2026-01-25', completedDate: '2026-01-24',
    estimate: '6h', estimatedHours: 6, actualTime: '7h', actualHours: 7,
    progress: 100, billable: true, hasEvidence: true, evidenceCount: 4,
    tags: ['brand', 'design-system', 'colors'], comments: 5, attachments: 3, storyPoints: 3,
    approvalStatus: 'Approved', client: 'StartupXYZ',
  },
  {
    id: 't31', taskId: 'MAR-030',
    title: 'Typography scale and font pairing',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm2', milestoneName: 'Phase 2: Design System',
    sprintId: 's2', sprintName: 'Sprint 3 — Core Features',
    assignee: 'Sarah Chen', assigneeDepartment: 'Product',
    status: 'Closed', priority: 'Medium',
    startDate: '2026-01-28', dueDate: '2026-02-07', completedDate: '2026-02-06',
    estimate: '3h', estimatedHours: 3, actualTime: '2h 45m', actualHours: 2.75,
    progress: 100, billable: true, hasEvidence: true, evidenceCount: 2,
    tags: ['typography', 'design-system'], comments: 2, storyPoints: 2,
    burnAmount: 275, profitImpact: 80, approvalStatus: 'Approved', client: 'TechCorp Inc',
  },
  {
    id: 't32', taskId: 'MAR-031',
    title: 'Component library documentation',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    sprintId: 's2', sprintName: 'Sprint 3 — Core Features',
    assignee: 'Mike Johnson', assigneeDepartment: 'Product',
    status: 'Closed', priority: 'Medium',
    startDate: '2026-01-30', dueDate: '2026-02-08', completedDate: '2026-02-07',
    estimate: '5h', estimatedHours: 5, actualTime: '5h 30m', actualHours: 5.5,
    progress: 100, billable: false, hasEvidence: false, evidenceCount: 0,
    tags: ['documentation', 'components'], comments: 3, storyPoints: 3,
    approvalStatus: 'Approved',
  },
  {
    id: 't33', taskId: 'ECP-024',
    title: 'User authentication (OAuth2 + JWT)',
    projectId: 'p2', projectName: 'E-commerce Platform', projectColor: '#ef4444',
    assignee: 'Lisa Wang', assigneeDepartment: 'Engineering',
    status: 'Closed', priority: 'High',
    startDate: '2026-01-15', dueDate: '2026-02-05', completedDate: '2026-02-04',
    estimate: '14h', estimatedHours: 14, actualTime: '16h', actualHours: 16,
    progress: 100, billable: true, hasEvidence: true, evidenceCount: 3,
    tags: ['auth', 'oauth', 'security'], comments: 8, storyPoints: 8,
    burnAmount: 1600, approvalStatus: 'Approved', client: 'RetailCo',
  },
  {
    id: 't34', taskId: 'PAV-044',
    title: 'Rate limiting middleware implementation',
    projectId: 'p4', projectName: 'Platform API v3', projectColor: '#8b5cf6',
    milestoneId: 'm7', milestoneName: 'Core Endpoints v3',
    sprintId: 's5', sprintName: 'Sprint 2 — API Core',
    assignee: 'Michael Brown', assigneeDepartment: 'Engineering',
    status: 'Closed', priority: 'High',
    startDate: '2026-01-20', dueDate: '2026-02-10', completedDate: '2026-02-08',
    estimate: '8h', estimatedHours: 8, actualTime: '9h', actualHours: 9,
    progress: 100, billable: false, hasEvidence: true, evidenceCount: 1,
    tags: ['middleware', 'rate-limiting', 'api'], comments: 4, storyPoints: 5,
    approvalStatus: 'Approved',
  },

  // ── OVERDUE (due before Feb 17, status not Closed) ────
  {
    id: 't2', taskId: 'ECP-011',
    title: 'Implement Stripe payment gateway',
    projectId: 'p2', projectName: 'E-commerce Platform', projectColor: '#ef4444',
    milestoneId: 'm5', milestoneName: 'Payment Integration',
    sprintId: 's3', sprintName: 'Sprint 5 — Payments',
    taskListId: 'tl3', taskListName: 'Checkout Module',
    assignee: 'Lisa Wang', assigneeDepartment: 'Engineering',
    status: 'Overdue', priority: 'Critical',
    startDate: '2026-01-10', dueDate: '2026-02-05',
    estimate: '16h', estimatedHours: 16, actualTime: '18h 15m', actualHours: 18.25,
    progress: 75, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['payments', 'stripe', 'backend'],
    description: 'Integrate Stripe payment gateway with webhooks and refund management',
    comments: 11, attachments: 3, storyPoints: 8,
    burnAmount: 1825, profitImpact: -200, approvalStatus: 'Approved', client: 'RetailCo',
  },
  {
    id: 't5', taskId: 'ECP-008',
    title: 'Fix checkout flow validation bug',
    projectId: 'p2', projectName: 'E-commerce Platform', projectColor: '#ef4444',
    milestoneId: 'm5', milestoneName: 'Payment Integration',
    sprintId: 's3', sprintName: 'Sprint 5 — Payments',
    taskListId: 'tl3', taskListName: 'Checkout Module',
    assignee: 'David Kim', assigneeDepartment: 'Engineering',
    status: 'Reopen', priority: 'High',
    dueDate: '2026-02-08',
    estimate: '6h', estimatedHours: 6, actualTime: '4h', actualHours: 4,
    progress: 50, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['bug', 'checkout', 'validation'],
    description: 'Reopened: fix didn\'t account for coupon + sale item edge case',
    comments: 6, storyPoints: 3, approvalStatus: 'Approved', client: 'RetailCo',
  },
  {
    id: 't17', taskId: 'MAR-025',
    title: 'Accessibility audit — WCAG 2.1 AA compliance',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    sprintId: 's1', sprintName: 'Sprint 4 — UX Polish',
    assignee: 'Sarah Chen', assigneeDepartment: 'Product',
    status: 'Overdue', priority: 'High',
    startDate: '2026-02-01', dueDate: '2026-02-12',
    estimate: '10h', estimatedHours: 10, actualTime: '6h', actualHours: 6,
    progress: 60, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['accessibility', 'audit', 'wcag'],
    description: 'Full WCAG 2.1 AA audit across all screens with remediation report',
    comments: 3, storyPoints: 5, burnAmount: 600, profitImpact: -80,
    approvalStatus: 'Approved', client: 'TechCorp Inc',
  },
  {
    id: 't18', taskId: 'PAV-042',
    title: 'Authentication JWT refresh token logic',
    projectId: 'p4', projectName: 'Platform API v3', projectColor: '#8b5cf6',
    milestoneId: 'm7', milestoneName: 'Core Endpoints v3',
    sprintId: 's5', sprintName: 'Sprint 2 — API Core',
    taskListId: 'tl4', taskListName: 'API Endpoints',
    assignee: 'Sophie Anderson', assigneeDepartment: 'Engineering',
    status: 'Overdue', priority: 'Critical',
    startDate: '2026-01-25', dueDate: '2026-02-08',
    estimate: '8h', estimatedHours: 8, actualTime: '5h', actualHours: 5,
    progress: 45, billable: false, hasEvidence: false, evidenceCount: 0,
    tags: ['auth', 'jwt', 'security'],
    description: 'Implement sliding window JWT refresh with rotation and blacklist',
    comments: 5, storyPoints: 8, approvalStatus: 'Approved',
  },
  {
    id: 't16', taskId: 'ECP-016',
    title: 'Inventory management sync with Shopify',
    projectId: 'p2', projectName: 'E-commerce Platform', projectColor: '#ef4444',
    milestoneId: 'm9', milestoneName: 'Frontend UI Build',
    sprintId: 's3', sprintName: 'Sprint 5 — Payments',
    assignee: 'James Taylor', assigneeDepartment: 'Engineering',
    status: 'In Progress', priority: 'High',
    startDate: '2026-02-05', dueDate: '2026-02-14',
    estimate: '12h', estimatedHours: 12, actualTime: '9h', actualHours: 9,
    progress: 70, billable: true, hasEvidence: true, evidenceCount: 2,
    tags: ['inventory', 'shopify', 'sync'],
    comments: 4, storyPoints: 8, burnAmount: 900, profitImpact: 150,
    approvalStatus: 'Approved', client: 'RetailCo',
  },

  // ── DUE TODAY — Feb 17, 2026 ──────────────────────────
  {
    id: 't19', taskId: 'MAR-026',
    title: 'Onboarding flow screens (Steps 1–4)',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    sprintId: 's1', sprintName: 'Sprint 4 — UX Polish',
    taskListId: 'tl1', taskListName: 'UI Components',
    assignee: 'Sarah Chen', assigneeDepartment: 'Product',
    status: 'In Progress', priority: 'High',
    startDate: '2026-02-13', dueDate: '2026-02-17',
    estimate: '8h', estimatedHours: 8, actualTime: '5h', actualHours: 5,
    progress: 62, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['onboarding', 'ux', 'screens'],
    description: 'Design and prototype all 4 onboarding screens with micro-interactions',
    comments: 3, storyPoints: 5, burnAmount: 500,
    subtasks: subtasksT19,
    approvalStatus: 'Approved', client: 'TechCorp Inc',
  },
  {
    id: 't20', taskId: 'MAR-027',
    title: 'Push notification permission flow',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    sprintId: 's1', sprintName: 'Sprint 4 — UX Polish',
    taskListId: 'tl2', taskListName: 'Navigation Flow',
    assignee: 'Mike Johnson', assigneeDepartment: 'Product',
    status: 'Open', priority: 'Medium',
    dueDate: '2026-02-17',
    estimate: '4h', estimatedHours: 4, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['push', 'notifications', 'permissions'],
    comments: 1, storyPoints: 3, approvalStatus: 'Approved',
  },
  {
    id: 't21', taskId: 'WRD-016',
    title: 'Hero section responsive layout',
    projectId: 'p3', projectName: 'Website Redesign', projectColor: '#10b981',
    milestoneId: 'm6', milestoneName: 'Visual Design Phase',
    taskListId: 'tl6', taskListName: 'Visual Mockups',
    assignee: 'Emma Wilson', assigneeDepartment: 'Design',
    status: 'In Progress', priority: 'High',
    startDate: '2026-02-14', dueDate: '2026-02-17',
    estimate: '6h', estimatedHours: 6, actualTime: '4h', actualHours: 4,
    progress: 66, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['responsive', 'hero', 'layout'],
    comments: 2, storyPoints: 3, approvalStatus: 'Approved', client: 'StartupXYZ',
  },

  // ── DUE THIS WEEK (Feb 18–24) ─────────────────────────
  {
    id: 't1', taskId: 'MAR-001',
    title: 'Design user authentication flow',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    sprintId: 's1', sprintName: 'Sprint 4 — UX Polish',
    taskListId: 'tl1', taskListName: 'UI Components',
    assignee: 'Sarah Chen', assigneeDepartment: 'Product',
    status: 'In Progress', priority: 'High',
    startDate: '2026-02-10', dueDate: '2026-02-20',
    estimate: '8h', estimatedHours: 8, actualTime: '5h 30m', actualHours: 5.5,
    progress: 68, billable: true, hasEvidence: true, evidenceCount: 3,
    tags: ['design', 'auth', 'security'],
    description: 'Complete redesign of authentication flow including SSO, biometric, and MFA options',
    comments: 4, attachments: 2, storyPoints: 5, burnAmount: 550, profitImpact: 200,
    subtasks: subtasksT1, approvalStatus: 'Approved', client: 'TechCorp Inc',
  },
  {
    id: 't3', taskId: 'PAV-034',
    title: 'Update API v3 documentation',
    projectId: 'p4', projectName: 'Platform API v3', projectColor: '#8b5cf6',
    milestoneId: 'm7', milestoneName: 'Core Endpoints v3',
    sprintId: 's5', sprintName: 'Sprint 2 — API Core',
    taskListId: 'tl4', taskListName: 'API Endpoints',
    assignee: 'Michael Brown', assigneeDepartment: 'Engineering',
    status: 'To Be Tested', priority: 'Medium',
    dueDate: '2026-02-18',
    estimate: '4h', estimatedHours: 4, actualTime: '3h 45m', actualHours: 3.75,
    progress: 90, billable: false, hasEvidence: true, evidenceCount: 1,
    tags: ['docs', 'api', 'openapi'],
    comments: 2, attachments: 1, storyPoints: 3,
    subtasks: subtasksT3, approvalStatus: 'Approved',
  },
  {
    id: 't8', taskId: 'ECP-014',
    title: 'Security audit & penetration testing',
    projectId: 'p2', projectName: 'E-commerce Platform', projectColor: '#ef4444',
    milestoneId: 'm5', milestoneName: 'Payment Integration',
    sprintId: 's3', sprintName: 'Sprint 5 — Payments',
    assignee: 'James Taylor', assigneeDepartment: 'Engineering',
    status: 'In Progress', priority: 'Critical',
    startDate: '2026-02-10', dueDate: '2026-02-20',
    estimate: '10h', estimatedHours: 10, actualTime: '6h', actualHours: 6,
    progress: 60, billable: true, hasEvidence: true, evidenceCount: 5,
    tags: ['security', 'audit', 'pentest'],
    comments: 8, attachments: 2, storyPoints: 8,
    burnAmount: 600, profitImpact: 150,
    subtasks: subtasksT8, approvalStatus: 'Approved', client: 'RetailCo',
  },
  {
    id: 't11', taskId: 'MAR-018',
    title: 'Onboarding animation system (Lottie)',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    sprintId: 's1', sprintName: 'Sprint 4 — UX Polish',
    taskListId: 'tl1', taskListName: 'UI Components',
    assignee: 'Emily Rodriguez', assigneeDepartment: 'Design',
    status: 'In Progress', priority: 'High',
    startDate: '2026-02-12', dueDate: '2026-02-21',
    estimate: '10h', estimatedHours: 10, actualTime: '4h', actualHours: 4,
    progress: 40, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['animation', 'onboarding', 'lottie'],
    comments: 3, storyPoints: 5, burnAmount: 400, profitImpact: 120,
    approvalStatus: 'Approved', client: 'TechCorp Inc',
  },
  {
    id: 't22', taskId: 'BIN-024',
    title: 'Prometheus monitoring stack setup',
    projectId: 'p5', projectName: 'Backend Infrastructure', projectColor: '#f59e0b',
    milestoneId: 'm8', milestoneName: 'Kubernetes Migration',
    assignee: 'Chris Johnson', assigneeDepartment: 'Operations',
    status: 'Open', priority: 'Medium',
    dueDate: '2026-02-19',
    estimate: '6h', estimatedHours: 6, actualTime: '0h', actualHours: 0,
    progress: 0, billable: false, hasEvidence: false, evidenceCount: 0,
    tags: ['monitoring', 'prometheus', 'devops'],
    comments: 2, storyPoints: 5, approvalStatus: 'Approved',
  },
  {
    id: 't23', taskId: 'ECP-022',
    title: 'Admin dashboard analytics widgets',
    projectId: 'p2', projectName: 'E-commerce Platform', projectColor: '#ef4444',
    milestoneId: 'm9', milestoneName: 'Frontend UI Build',
    sprintId: 's3', sprintName: 'Sprint 5 — Payments',
    assignee: 'David Kim', assigneeDepartment: 'Engineering',
    status: 'Open', priority: 'Medium',
    dueDate: '2026-02-24',
    estimate: '8h', estimatedHours: 8, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['admin', 'analytics', 'dashboard'],
    comments: 1, storyPoints: 5, approvalStatus: 'Approved', client: 'RetailCo',
  },

  // ── UPCOMING (Feb 25 – March) ──────────────────────────
  {
    id: 't7', taskId: 'MAR-012',
    title: 'CI/CD pipeline — GitHub Actions (iOS/Android)',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    sprintId: 's1', sprintName: 'Sprint 4 — UX Polish',
    taskListId: 'tl2', taskListName: 'Navigation Flow',
    assignee: 'Mike Johnson', assigneeDepartment: 'Product',
    status: 'Pending Review', priority: 'Medium',
    dueDate: '2026-02-28',
    estimate: '8h', estimatedHours: 8, actualTime: '8h', actualHours: 8,
    progress: 100, billable: false, hasEvidence: false, evidenceCount: 0,
    tags: ['ci-cd', 'github-actions', 'devops'],
    comments: 2, storyPoints: 5,
    submittedByEmployee: true, submittedBy: 'Mike Johnson',
    description: 'Automated deployment pipeline for both iOS (TestFlight) and Android (Play Store) builds',
    approvalStatus: 'Pending Approval',
  },
  {
    id: 't9', taskId: 'WRD-012',
    title: 'Mobile responsive layout — all breakpoints',
    projectId: 'p3', projectName: 'Website Redesign', projectColor: '#10b981',
    milestoneId: 'm6', milestoneName: 'Visual Design Phase',
    taskListId: 'tl6', taskListName: 'Visual Mockups',
    assignee: 'Alex Martinez', assigneeDepartment: 'Design',
    status: 'Open', priority: 'Medium',
    dueDate: '2026-03-05',
    estimate: '6h', estimatedHours: 6, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['testing', 'responsive', 'mobile'],
    comments: 0, storyPoints: 3, approvalStatus: 'Approved', client: 'StartupXYZ',
  },
  {
    id: 't10', taskId: 'PAV-041',
    title: 'GraphQL schema design & federation setup',
    projectId: 'p4', projectName: 'Platform API v3', projectColor: '#8b5cf6',
    milestoneId: 'm10', milestoneName: 'GraphQL Layer',
    assignee: 'Sophie Anderson', assigneeDepartment: 'Engineering',
    status: 'On Hold', priority: 'Low',
    dueDate: '2026-03-20',
    estimate: '5h', estimatedHours: 5, actualTime: '0h', actualHours: 0,
    progress: 0, billable: false, hasEvidence: false, evidenceCount: 0,
    tags: ['graphql', 'schema', 'federation'],
    comments: 5, storyPoints: 5,
    description: 'On hold pending architecture team sign-off on federation approach',
    approvalStatus: 'Approved',
  },
  {
    id: 't12', taskId: 'BIN-023',
    title: 'Kubernetes cluster HA configuration',
    projectId: 'p5', projectName: 'Backend Infrastructure', projectColor: '#f59e0b',
    milestoneId: 'm8', milestoneName: 'Kubernetes Migration',
    assignee: 'Maria Garcia', assigneeDepartment: 'Operations',
    status: 'Waiting', priority: 'High',
    dueDate: '2026-03-15',
    estimate: '12h', estimatedHours: 12, actualTime: '3h', actualHours: 3,
    progress: 25, billable: false, hasEvidence: false, evidenceCount: 0,
    tags: ['kubernetes', 'ha', 'infra'],
    comments: 6, storyPoints: 8,
    description: 'Waiting for cloud vendor provisioning confirmation (GCP quotas)',
    approvalStatus: 'Approved',
  },
  {
    id: 't13', taskId: 'ECP-020',
    title: 'Product catalog search & Elasticsearch',
    projectId: 'p2', projectName: 'E-commerce Platform', projectColor: '#ef4444',
    milestoneId: 'm9', milestoneName: 'Frontend UI Build',
    sprintId: 's4', sprintName: 'Sprint 6 — Launch Prep',
    taskListId: 'tl3', taskListName: 'Checkout Module',
    assignee: 'David Kim', assigneeDepartment: 'Engineering',
    status: 'Open', priority: 'Medium',
    dueDate: '2026-02-25',
    estimate: '14h', estimatedHours: 14, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['search', 'elasticsearch', 'catalog'],
    comments: 2, storyPoints: 8, approvalStatus: 'Approved', client: 'RetailCo',
  },
  {
    id: 't15', taskId: 'MAR-022',
    title: 'Dark mode — complete implementation',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    sprintId: 's1', sprintName: 'Sprint 4 — UX Polish',
    taskListId: 'tl1', taskListName: 'UI Components',
    assignee: 'Mike Johnson', assigneeDepartment: 'Product',
    status: 'Open', priority: 'Medium',
    dueDate: '2026-02-28',
    estimate: '6h', estimatedHours: 6, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['dark-mode', 'theming', 'tokens'],
    comments: 1, storyPoints: 3, approvalStatus: 'Approved',
  },
  {
    id: 't24', taskId: 'ECP-023',
    title: 'Order tracking real-time updates (WebSocket)',
    projectId: 'p2', projectName: 'E-commerce Platform', projectColor: '#ef4444',
    milestoneId: 'm9', milestoneName: 'Frontend UI Build',
    sprintId: 's4', sprintName: 'Sprint 6 — Launch Prep',
    assignee: 'Lisa Wang', assigneeDepartment: 'Engineering',
    status: 'In Progress', priority: 'High',
    startDate: '2026-02-14', dueDate: '2026-02-27',
    estimate: '12h', estimatedHours: 12, actualTime: '4h', actualHours: 4,
    progress: 33, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['websocket', 'realtime', 'orders'],
    comments: 3, storyPoints: 8,
    burnAmount: 400, approvalStatus: 'Approved', client: 'RetailCo',
  },
  {
    id: 't25', taskId: 'PAV-043',
    title: 'Webhook delivery & retry system',
    projectId: 'p4', projectName: 'Platform API v3', projectColor: '#8b5cf6',
    milestoneId: 'm7', milestoneName: 'Core Endpoints v3',
    sprintId: 's5', sprintName: 'Sprint 2 — API Core',
    taskListId: 'tl4', taskListName: 'API Endpoints',
    assignee: 'Michael Brown', assigneeDepartment: 'Engineering',
    status: 'To Be Tested', priority: 'Medium',
    startDate: '2026-02-10', dueDate: '2026-03-01',
    estimate: '8h', estimatedHours: 8, actualTime: '7h 30m', actualHours: 7.5,
    progress: 85, billable: false, hasEvidence: true, evidenceCount: 2,
    tags: ['webhooks', 'retry', 'queue'],
    comments: 4, storyPoints: 5, approvalStatus: 'Approved',
  },
  {
    id: 't26', taskId: 'WRD-018',
    title: 'Blog section design & CMS integration',
    projectId: 'p3', projectName: 'Website Redesign', projectColor: '#10b981',
    milestoneId: 'm6', milestoneName: 'Visual Design Phase',
    taskListId: 'tl6', taskListName: 'Visual Mockups',
    assignee: 'Emma Wilson', assigneeDepartment: 'Design',
    status: 'Open', priority: 'Low',
    dueDate: '2026-03-08',
    estimate: '8h', estimatedHours: 8, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['blog', 'cms', 'design'],
    comments: 0, storyPoints: 5, approvalStatus: 'Approved', client: 'StartupXYZ',
  },
  {
    id: 't27', taskId: 'MAR-028',
    title: 'Settings screen — full redesign',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    assignee: 'Sarah Chen', assigneeDepartment: 'Product',
    status: 'Open', priority: 'Low',
    dueDate: '2026-03-10',
    estimate: '5h', estimatedHours: 5, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['settings', 'ux', 'redesign'],
    comments: 0, storyPoints: 3, approvalStatus: 'Approved', client: 'TechCorp Inc',
  },
  {
    id: 't28', taskId: 'MAR-029',
    title: 'Loading states & skeleton screens',
    projectId: 'p1', projectName: 'Mobile App Redesign', projectColor: '#3b82f6',
    milestoneId: 'm3', milestoneName: 'Phase 3: Core Development',
    sprintId: 's1', sprintName: 'Sprint 4 — UX Polish',
    taskListId: 'tl1', taskListName: 'UI Components',
    assignee: 'Emily Rodriguez', assigneeDepartment: 'Design',
    status: 'Waiting', priority: 'Medium',
    dueDate: '2026-03-12',
    estimate: '6h', estimatedHours: 6, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['loading', 'skeleton', 'ux'],
    description: 'Waiting for finalized component library from design system team',
    comments: 1, storyPoints: 3, approvalStatus: 'Approved',
  },
  {
    id: 't29', taskId: 'WRD-019',
    title: 'SEO metadata & structured data',
    projectId: 'p3', projectName: 'Website Redesign', projectColor: '#10b981',
    assignee: 'Alex Martinez', assigneeDepartment: 'Design',
    status: 'Open', priority: 'Low',
    dueDate: '2026-03-20',
    estimate: '4h', estimatedHours: 4, actualTime: '0h', actualHours: 0,
    progress: 0, billable: true, hasEvidence: false, evidenceCount: 0,
    tags: ['seo', 'metadata', 'schema'],
    comments: 0, storyPoints: 3, approvalStatus: 'Approved', client: 'StartupXYZ',
  },
  {
    id: 't30', taskId: 'BIN-025',
    title: 'Grafana dashboard setup for K8s metrics',
    projectId: 'p5', projectName: 'Backend Infrastructure', projectColor: '#f59e0b',
    milestoneId: 'm8', milestoneName: 'Kubernetes Migration',
    assignee: 'Chris Johnson', assigneeDepartment: 'Operations',
    status: 'In Progress', priority: 'Medium',
    startDate: '2026-02-15', dueDate: '2026-03-05',
    estimate: '8h', estimatedHours: 8, actualTime: '2h', actualHours: 2,
    progress: 25, billable: false, hasEvidence: false, evidenceCount: 0,
    tags: ['grafana', 'monitoring', 'k8s'],
    comments: 2, storyPoints: 5, approvalStatus: 'Approved',
  },

  // ── SPECIAL STATUSES ──────────────────────────────────
  {
    id: 't35', taskId: "PAV-045",
    title: "IE11 compatibility polyfills (legacy)",
    projectId: 'p4', projectName: 'Platform API v3', projectColor: '#8b5cf6',
    assignee: 'Sophie Anderson', assigneeDepartment: 'Engineering',
    status: "Won't Fix", priority: 'None',
    dueDate: '2026-03-15',
    estimate: '12h', estimatedHours: 12, actualTime: '0h', actualHours: 0,
    progress: 0, billable: false, hasEvidence: false, evidenceCount: 0,
    tags: ['legacy', 'ie11', 'wontfix'],
    description: "IE11 reached EOL. Will not be implementing compatibility layer.",
    comments: 3, storyPoints: 8, approvalStatus: 'Rejected',
  },
];

// ─── Issues ────────────────────────────────────────────────
export const mockIssues: Issue[] = [
  {
    id: 'i1', issueId: 'ECP-BUG-001',
    title: 'Checkout total incorrect with stacked discounts',
    projectId: 'p2', projectName: 'E-commerce Platform',
    status: 'In Progress', severity: 'Critical',
    assignee: 'David Kim', reporter: 'James Taylor',
    dueDate: '2026-02-18', createdAt: '2026-02-10',
    module: 'Checkout', reproducible: 'Always',
    description: 'When applying a promo code alongside a sale item, the total is calculated before the sale discount is applied resulting in overcharging.',
    linkedTaskId: 't5', comments: 7,
  },
  {
    id: 'i2', issueId: 'MAR-BUG-004',
    title: 'Back gesture conflicts with swipe-to-dismiss drawer',
    projectId: 'p1', projectName: 'Mobile App Redesign',
    status: 'Open', severity: 'Major',
    assignee: 'Sarah Chen', reporter: 'Emily Rodriguez',
    dueDate: '2026-02-22', createdAt: '2026-02-12',
    module: 'Navigation', reproducible: 'Sometimes', comments: 3,
  },
  {
    id: 'i3', issueId: 'PAV-BUG-002',
    title: 'Rate limiting bypassed on batch API endpoints',
    projectId: 'p4', projectName: 'Platform API v3',
    status: 'Open', severity: 'Major',
    assignee: 'Michael Brown', reporter: 'Sophie Anderson',
    dueDate: '2026-02-25', createdAt: '2026-02-08',
    module: 'API Gateway', reproducible: 'Always', comments: 4,
  },
  {
    id: 'i4', issueId: 'ECP-BUG-007',
    title: 'Product images fail to load on 3G connections',
    projectId: 'p2', projectName: 'E-commerce Platform',
    status: 'Resolved', severity: 'Minor',
    assignee: 'Lisa Wang', reporter: 'David Kim',
    dueDate: '2026-02-15', createdAt: '2026-02-01',
    module: 'Product Catalog', reproducible: 'Sometimes', comments: 2,
  },
  {
    id: 'i5', issueId: 'WRD-BUG-001',
    title: 'Footer nav links broken on iOS Safari 16',
    projectId: 'p3', projectName: 'Website Redesign',
    status: 'Open', severity: 'Minor',
    assignee: 'Alex Martinez', reporter: 'Emma Wilson',
    dueDate: '2026-03-01', createdAt: '2026-02-14',
    module: 'Footer', reproducible: 'Always', comments: 1,
  },
  {
    id: 'i6', issueId: 'ECP-BUG-012',
    title: 'Payment webhook duplicate events causing double charges',
    projectId: 'p2', projectName: 'E-commerce Platform',
    status: 'In Progress', severity: 'Critical',
    assignee: 'Lisa Wang', reporter: 'James Taylor',
    dueDate: '2026-02-19', createdAt: '2026-02-15',
    module: 'Payments', reproducible: 'Sometimes', comments: 9,
  },
  {
    id: 'i7', issueId: 'BIN-BUG-003',
    title: 'Memory leak in API gateway after 24h uptime',
    projectId: 'p5', projectName: 'Backend Infrastructure',
    status: 'Open', severity: 'Major',
    assignee: 'Maria Garcia', reporter: 'Chris Johnson',
    dueDate: '2026-02-28', createdAt: '2026-02-13',
    module: 'API Gateway', reproducible: 'Always', comments: 5,
  },
  {
    id: 'i8', issueId: 'MAR-BUG-005',
    title: 'Dark mode: text contrast fails on input fields',
    projectId: 'p1', projectName: 'Mobile App Redesign',
    status: 'Open', severity: 'Major',
    assignee: 'Emily Rodriguez', reporter: 'Sarah Chen',
    dueDate: '2026-02-24', createdAt: '2026-02-16',
    module: 'Design System', reproducible: 'Always', comments: 2,
  },
];

// ─── Time Logs ─────────────────────────────────────────────
export const mockTimeLogs: TimeLog[] = [
  { id: 'tl01', taskId: 't1',  date: '2026-02-14', duration: '2h 30m', hours: 2.5, description: 'Worked on login screen wireframe and SSO flow diagram', loggedBy: 'Sarah Chen', billable: true },
  { id: 'tl02', taskId: 't1',  date: '2026-02-13', duration: '3h', hours: 3, description: 'Authentication flow design review with PM', loggedBy: 'Sarah Chen', billable: true },
  { id: 'tl03', taskId: 't2',  date: '2026-02-14', duration: '4h', hours: 4, description: 'Stripe webhook implementation and testing', loggedBy: 'Lisa Wang', billable: true },
  { id: 'tl04', taskId: 't8',  date: '2026-02-13', duration: '3h', hours: 3, description: 'Phase 1 penetration testing — authentication endpoints', loggedBy: 'James Taylor', billable: true },
  { id: 'tl05', taskId: 't11', date: '2026-02-14', duration: '2h', hours: 2, description: 'Splash screen animation prototype in After Effects', loggedBy: 'Emily Rodriguez', billable: true },
  { id: 'tl06', taskId: 't19', date: '2026-02-17', duration: '2h 30m', hours: 2.5, description: 'Onboarding step 1 & 2 screens — hi-fi prototypes', loggedBy: 'Sarah Chen', billable: true },
  { id: 'tl07', taskId: 't16', date: '2026-02-16', duration: '4h', hours: 4, description: 'Shopify API integration setup and webhook testing', loggedBy: 'James Taylor', billable: true },
  { id: 'tl08', taskId: 't24', date: '2026-02-16', duration: '2h', hours: 2, description: 'WebSocket server setup and order event schema', loggedBy: 'Lisa Wang', billable: true },
  { id: 'tl09', taskId: 't3',  date: '2026-02-15', duration: '3h 45m', hours: 3.75, description: 'OpenAPI 3.0 spec updates and Swagger UI customization', loggedBy: 'Michael Brown', billable: false },
  { id: 'tl10', taskId: 't25', date: '2026-02-15', duration: '3h 30m', hours: 3.5, description: 'Webhook retry queue with exponential backoff', loggedBy: 'Michael Brown', billable: false },
  { id: 'tl11', taskId: 't17', date: '2026-02-14', duration: '3h', hours: 3, description: 'WCAG audit — color contrast and screen reader testing', loggedBy: 'Sarah Chen', billable: true },
  { id: 'tl12', taskId: 't30', date: '2026-02-16', duration: '2h', hours: 2, description: 'Grafana dashboard initial setup and K8s data source', loggedBy: 'Chris Johnson', billable: false },
  { id: 'tl13', taskId: 't4',  date: '2026-02-14', duration: '4h', hours: 4, description: 'Landing page hero section, nav and feature blocks', loggedBy: 'Emma Wilson', billable: true },
  { id: 'tl14', taskId: 't4',  date: '2026-02-13', duration: '3h', hours: 3, description: 'Services section and testimonials block design', loggedBy: 'Emma Wilson', billable: true },
  { id: 'tl15', taskId: 't21', date: '2026-02-17', duration: '4h', hours: 4, description: 'Hero responsive breakpoints — sm, md, lg, xl', loggedBy: 'Emma Wilson', billable: true },
  { id: 'tl16', taskId: 't8',  date: '2026-02-15', duration: '3h', hours: 3, description: 'XSS and CSRF vulnerability assessment', loggedBy: 'James Taylor', billable: true },
  { id: 'tl17', taskId: 't33', date: '2026-02-04', duration: '6h', hours: 6, description: 'OAuth2 PKCE flow and JWT signing/verification', loggedBy: 'Lisa Wang', billable: true },
  { id: 'tl18', taskId: 't34', date: '2026-02-08', duration: '4h', hours: 4, description: 'Redis sliding window rate limiter implementation', loggedBy: 'Michael Brown', billable: false },
  { id: 'tl19', taskId: 't13', date: '2026-02-16', duration: '5h', hours: 5, description: 'Elasticsearch index mappings and query DSL setup', loggedBy: 'David Kim', billable: true },
  { id: 'tl20', taskId: 't5',  date: '2026-02-14', duration: '2h', hours: 2, description: 'Reproducing coupon + sale item edge case bug', loggedBy: 'David Kim', billable: true },
  { id: 'tl21', taskId: 't12', date: '2026-02-15', duration: '3h', hours: 3, description: 'K8s cluster HA setup — waiting on GCP quota', loggedBy: 'Maria Garcia', billable: false },
  { id: 'tl22', taskId: 't1',  date: '2026-02-12', duration: '2h', hours: 2, description: 'Biometric auth research — Face ID / Fingerprint APIs', loggedBy: 'Sarah Chen', billable: true },
  { id: 'tl23', taskId: 't18', date: '2026-02-07', duration: '5h', hours: 5, description: 'JWT rotation logic and blacklist Redis store', loggedBy: 'Sophie Anderson', billable: false },
  { id: 'tl24', taskId: 't11', date: '2026-02-16', duration: '2h', hours: 2, description: 'Lottie animation step 2 — in progress', loggedBy: 'Emily Rodriguez', billable: true },
];

// ─── Project Documents ─────────────────────────────────────
export interface ProjectDocument {
  id: string;
  projectId: string;
  projectName: string;
  name: string;
  type: 'PDF' | 'FIGMA' | 'XLSX' | 'DOCX' | 'MP4' | 'ZIP' | 'PPTX' | 'PNG';
  size: string;
  version: string;
  uploadedBy: string;
  uploadedAt: string;
  description?: string;
  tags?: string[];
  folder?: string;
}

export const mockDocuments: ProjectDocument[] = [
  // ── Mobile App Redesign (p1) ──
  { id: 'd1',  projectId: 'p1', projectName: 'Mobile App Redesign', name: 'MAR — Product Requirements Document', type: 'DOCX', size: '248 KB', version: 'v2.4', uploadedBy: 'Sarah Chen', uploadedAt: '2026-02-10', folder: 'Specifications', description: 'Full PRD including user stories, acceptance criteria and out-of-scope items', tags: ['prd', 'requirements'] },
  { id: 'd2',  projectId: 'p1', projectName: 'Mobile App Redesign', name: 'Design System — Figma Source File', type: 'FIGMA', size: '4.2 MB', version: 'v3.1', uploadedBy: 'Sarah Chen', uploadedAt: '2026-02-14', folder: 'Design', description: 'Complete Figma design file with components, tokens and all screen designs', tags: ['figma', 'design-system'] },
  { id: 'd3',  projectId: 'p1', projectName: 'Mobile App Redesign', name: 'Sprint 4 Demo Recording', type: 'MP4', size: '187 MB', version: 'v1.0', uploadedBy: 'Mike Johnson', uploadedAt: '2026-02-13', folder: 'Demos', description: 'Screen recording of Sprint 4 live demo for TechCorp Inc stakeholders', tags: ['demo', 'sprint-4'] },
  { id: 'd4',  projectId: 'p1', projectName: 'Mobile App Redesign', name: 'WCAG 2.1 Audit Report', type: 'PDF', size: '1.1 MB', version: 'v1.0', uploadedBy: 'Sarah Chen', uploadedAt: '2026-02-15', folder: 'QA', description: 'Partial WCAG 2.1 AA accessibility audit — 14 issues found across 8 screens', tags: ['accessibility', 'audit'] },
  { id: 'd5',  projectId: 'p1', projectName: 'Mobile App Redesign', name: 'Budget & Timeline Tracker', type: 'XLSX', size: '88 KB', version: 'v5.2', uploadedBy: 'Sarah Chen', uploadedAt: '2026-02-11', folder: 'Finance', description: 'Live budget vs actuals and milestone schedule tracker', tags: ['budget', 'timeline'] },
  { id: 'd6',  projectId: 'p1', projectName: 'Mobile App Redesign', name: 'Technical Architecture Deck', type: 'PPTX', size: '3.8 MB', version: 'v1.3', uploadedBy: 'Mike Johnson', uploadedAt: '2026-01-28', folder: 'Architecture', description: 'System architecture, API integration map and data flow diagrams', tags: ['architecture', 'technical'] },
  // ── E-commerce Platform (p2) ──
  { id: 'd7',  projectId: 'p2', projectName: 'E-commerce Platform', name: 'Payment Gateway Integration Spec', type: 'PDF', size: '2.3 MB', version: 'v1.6', uploadedBy: 'Lisa Wang', uploadedAt: '2026-02-12', folder: 'Specifications', description: 'Stripe API integration specification including webhook events and error codes', tags: ['stripe', 'payments', 'spec'] },
  { id: 'd8',  projectId: 'p2', projectName: 'E-commerce Platform', name: 'Security Audit Pentest Report', type: 'PDF', size: '4.7 MB', version: 'v1.0', uploadedBy: 'James Taylor', uploadedAt: '2026-02-16', folder: 'Security', description: 'Phase 1 penetration testing report — 3 critical, 5 major vulnerabilities found', tags: ['security', 'pentest'] },
  { id: 'd9',  projectId: 'p2', projectName: 'E-commerce Platform', name: 'UI Wireframes — All Screens', type: 'FIGMA', size: '6.1 MB', version: 'v2.0', uploadedBy: 'David Kim', uploadedAt: '2026-02-08', folder: 'Design', description: 'Complete wireframes for 42 screens including checkout, product and admin flows', tags: ['wireframes', 'ui'] },
  { id: 'd10', projectId: 'p2', projectName: 'E-commerce Platform', name: 'Load Test Results — Staging', type: 'XLSX', size: '156 KB', version: 'v2.1', uploadedBy: 'James Taylor', uploadedAt: '2026-02-07', folder: 'QA', description: 'Artillery.js load test results — 500 RPS sustained, P99 latency 340ms', tags: ['load-test', 'performance'] },
  // ── Website Redesign (p3) ──
  { id: 'd11', projectId: 'p3', projectName: 'Website Redesign', name: 'Brand Identity Guide v1.0', type: 'PDF', size: '8.4 MB', version: 'v1.0', uploadedBy: 'Emma Wilson', uploadedAt: '2026-02-01', folder: 'Brand', description: 'Complete brand identity guide: colors, typography, logo usage and illustrations', tags: ['brand', 'identity'] },
  { id: 'd12', projectId: 'p3', projectName: 'Website Redesign', name: 'Component Library — Figma', type: 'FIGMA', size: '5.2 MB', version: 'v2.3', uploadedBy: 'Emma Wilson', uploadedAt: '2026-02-14', folder: 'Design', description: '84 components across 12 categories ready for developer handoff', tags: ['components', 'design-system'] },
  { id: 'd13', projectId: 'p3', projectName: 'Website Redesign', name: 'SEO & Content Strategy', type: 'DOCX', size: '312 KB', version: 'v1.1', uploadedBy: 'Alex Martinez', uploadedAt: '2026-02-05', folder: 'Content', description: 'Keyword strategy, meta templates and content migration plan', tags: ['seo', 'content'] },
  // ── Platform API v3 (p4) ──
  { id: 'd14', projectId: 'p4', projectName: 'Platform API v3', name: 'OpenAPI 3.0 Specification', type: 'PDF', size: '1.8 MB', version: 'v3.0-beta', uploadedBy: 'Michael Brown', uploadedAt: '2026-02-16', folder: 'Specifications', description: 'Complete OpenAPI 3.0 spec with 86 endpoints, request/response schemas and examples', tags: ['openapi', 'api-spec'] },
  { id: 'd15', projectId: 'p4', projectName: 'Platform API v3', name: 'GraphQL Schema Draft', type: 'DOCX', size: '94 KB', version: 'v0.3-draft', uploadedBy: 'Sophie Anderson', uploadedAt: '2026-02-10', folder: 'Architecture', description: 'Proposed GraphQL schema for v3 — pending architecture team sign-off', tags: ['graphql', 'schema', 'draft'] },
  { id: 'd16', projectId: 'p4', projectName: 'Platform API v3', name: 'Rate Limiting Policy Document', type: 'PDF', size: '420 KB', version: 'v1.2', uploadedBy: 'Michael Brown', uploadedAt: '2026-02-09', folder: 'Specifications', description: 'Rate limiting policy, quota tiers and Redis implementation details', tags: ['rate-limiting', 'policy'] },
  // ── Backend Infrastructure (p5) ──
  { id: 'd17', projectId: 'p5', projectName: 'Backend Infrastructure', name: 'K8s Migration Runbook v2.0', type: 'DOCX', size: '178 KB', version: 'v2.0', uploadedBy: 'Chris Johnson', uploadedAt: '2026-02-12', folder: 'Operations', description: 'Step-by-step Kubernetes migration runbook with rollback procedures', tags: ['kubernetes', 'runbook'] },
  { id: 'd18', projectId: 'p5', projectName: 'Backend Infrastructure', name: 'Infrastructure Architecture Diagram', type: 'PNG', size: '3.1 MB', version: 'v1.4', uploadedBy: 'Maria Garcia', uploadedAt: '2026-02-08', folder: 'Architecture', description: 'GCP infrastructure diagram — VPCs, clusters, load balancers and databases', tags: ['infrastructure', 'gcp'] },
];

// ─── Sprint Burndown Data ─────────────────────────────────
export interface BurndownPoint {
  day: string;
  date: string;
  ideal: number;
  actual?: number;
}

export const mockBurndownSprint5: BurndownPoint[] = [
  { day: 'Feb 3',  date: '2026-02-03', ideal: 55,   actual: 55   },
  { day: 'Feb 4',  date: '2026-02-04', ideal: 50.9, actual: 52   },
  { day: 'Feb 5',  date: '2026-02-05', ideal: 46.9, actual: 48   },
  { day: 'Feb 6',  date: '2026-02-06', ideal: 42.8, actual: 44.5 },
  { day: 'Feb 7',  date: '2026-02-07', ideal: 38.8, actual: 41   },
  { day: 'Feb 10', date: '2026-02-10', ideal: 34.7, actual: 37   },
  { day: 'Feb 11', date: '2026-02-11', ideal: 30.7, actual: 31   },
  { day: 'Feb 12', date: '2026-02-12', ideal: 26.6, actual: 27   },
  { day: 'Feb 13', date: '2026-02-13', ideal: 22.5, actual: 25.5 },
  { day: 'Feb 14', date: '2026-02-14', ideal: 18.5, actual: 22   },
  { day: 'Feb 17', date: '2026-02-17', ideal: 14.4, actual: 17   },
  { day: 'Feb 18', date: '2026-02-18', ideal: 10.4, actual: undefined },
  { day: 'Feb 19', date: '2026-02-19', ideal: 6.3,  actual: undefined },
  { day: 'Feb 20', date: '2026-02-20', ideal: 2.3,  actual: undefined },
];

// ─── Activity Feed ─────────────────────────────────────────
export interface ActivityEntry {
  id: string;
  type: 'task_completed' | 'task_started' | 'comment_added' | 'status_changed' | 'task_assigned' | 'milestone_reached' | 'sprint_started' 
    | 'task_created' | 'task_updated' | 'task_deleted' | 'email_created' | 'email_deleted' | 'email_linked' 
    | 'project_created' | 'project_deleted' | 'milestone_created' | 'milestone_deleted' | 'sprint_created' | 'sprint_deleted';
  actor: string;
  actorInitial: string;
  message: string;
  target: string;
  projectName: string;
  projectColor: string;
  timestamp: string;
  link?: string;
}

export const mockActivityFeed: ActivityEntry[] = [
  { id: 'a1',  type: 'task_completed',  actor: 'Emma Wilson',     actorInitial: 'E', message: 'completed',         target: 'Create landing page mockups',          projectName: 'Website Redesign',     projectColor: '#10b981', timestamp: '2026-02-14T15:30:00' },
  { id: 'a2',  type: 'status_changed',  actor: 'Lisa Wang',       actorInitial: 'L', message: 'marked as Overdue', target: 'Implement Stripe payment gateway',      projectName: 'E-commerce Platform',  projectColor: '#ef4444', timestamp: '2026-02-14T11:20:00' },
  { id: 'a3',  type: 'comment_added',   actor: 'David Kim',       actorInitial: 'D', message: 'commented on',      target: 'Fix checkout flow validation bug',      projectName: 'E-commerce Platform',  projectColor: '#ef4444', timestamp: '2026-02-14T10:05:00' },
  { id: 'a4',  type: 'task_started',    actor: 'Sarah Chen',      actorInitial: 'S', message: 'started work on',   target: 'Onboarding flow screens (Steps 1–4)',   projectName: 'Mobile App Redesign',  projectColor: '#3b82f6', timestamp: '2026-02-13T09:15:00' },
  { id: 'a5',  type: 'milestone_reached',actor: 'Sarah Chen',     actorInitial: 'S', message: 'completed milestone', target: 'Phase 2: Design System',              projectName: 'Mobile App Redesign',  projectColor: '#3b82f6', timestamp: '2026-02-13T17:00:00' },
  { id: 'a6',  type: 'task_completed',  actor: 'Chris Johnson',   actorInitial: 'C', message: 'completed',         target: 'PostgreSQL query optimization',         projectName: 'Backend Infrastructure',projectColor: '#f59e0b', timestamp: '2026-02-09T16:45:00' },
  { id: 'a7',  type: 'status_changed',  actor: 'Michael Brown',   actorInitial: 'M', message: 'moved to Testing',  target: 'Update API v3 documentation',          projectName: 'Platform API v3',      projectColor: '#8b5cf6', timestamp: '2026-02-15T14:30:00' },
  { id: 'a8',  type: 'sprint_started',  actor: 'Sarah Chen',      actorInitial: 'S', message: 'started sprint',    target: 'Sprint 4 — UX Polish',                 projectName: 'Mobile App Redesign',  projectColor: '#3b82f6', timestamp: '2026-02-10T09:00:00' },
  { id: 'a9',  type: 'task_assigned',   actor: 'James Taylor',    actorInitial: 'J', message: 'assigned to',       target: 'Security audit & penetration testing',  projectName: 'E-commerce Platform',  projectColor: '#ef4444', timestamp: '2026-02-10T10:30:00' },
  { id: 'a10', type: 'comment_added',   actor: 'Emily Rodriguez', actorInitial: 'E', message: 'commented on',      target: 'Onboarding animation system (Lottie)',  projectName: 'Mobile App Redesign',  projectColor: '#3b82f6', timestamp: '2026-02-16T11:20:00' },
  { id: 'a11', type: 'status_changed',  actor: 'Sophie Anderson', actorInitial: 'S', message: 'put on hold',       target: 'GraphQL schema design & federation',    projectName: 'Platform API v3',      projectColor: '#8b5cf6', timestamp: '2026-02-15T16:00:00' },
  { id: 'a12', type: 'task_completed',  actor: 'Mike Johnson',    actorInitial: 'M', message: 'completed',         target: 'Component library documentation',       projectName: 'Mobile App Redesign',  projectColor: '#3b82f6', timestamp: '2026-02-07T17:30:00' },
];

// ─── Team Members ──────────────────────────────────────────
export const mockTeamMembers: TeamMember[] = [
  { id: 'tm1',  name: 'Sarah Chen',      department: 'Product',     role: 'Product Manager',         currentLoad: 88, capacity: 40, assignedTasks: 9,  completedTasks: 12, skills: ['Product', 'UX', 'Strategy'],             availability: 5  },
  { id: 'tm2',  name: 'David Kim',       department: 'Engineering', role: 'Senior Developer',        currentLoad: 95, capacity: 40, assignedTasks: 12, completedTasks: 18, skills: ['React', 'Node.js', 'PostgreSQL'],         availability: 2  },
  { id: 'tm3',  name: 'Emma Wilson',     department: 'Design',      role: 'Lead Designer',           currentLoad: 72, capacity: 40, assignedTasks: 6,  completedTasks: 9,  skills: ['Figma', 'Brand', 'UI/UX'],               availability: 11 },
  { id: 'tm4',  name: 'Michael Brown',   department: 'Engineering', role: 'Backend Developer',       currentLoad: 80, capacity: 40, assignedTasks: 10, completedTasks: 15, skills: ['Python', 'AWS', 'GraphQL'],              availability: 8  },
  { id: 'tm5',  name: 'Lisa Wang',       department: 'Engineering', role: 'Full Stack Developer',    currentLoad: 93, capacity: 40, assignedTasks: 11, completedTasks: 14, skills: ['Vue.js', 'Laravel', 'Stripe'],           availability: 3  },
  { id: 'tm6',  name: 'Chris Johnson',   department: 'Operations',  role: 'DevOps Engineer',         currentLoad: 68, capacity: 40, assignedTasks: 5,  completedTasks: 20, skills: ['Kubernetes', 'Terraform', 'GCP'],        availability: 13 },
  { id: 'tm7',  name: 'Mike Johnson',    department: 'Product',     role: 'Mobile Developer',        currentLoad: 78, capacity: 40, assignedTasks: 8,  completedTasks: 11, skills: ['React Native', 'Swift', 'Kotlin'],       availability: 9  },
  { id: 'tm8',  name: 'Emily Rodriguez', department: 'Design',      role: 'UI/Motion Designer',      currentLoad: 65, capacity: 40, assignedTasks: 7,  completedTasks: 8,  skills: ['Figma', 'After Effects', 'Lottie'],     availability: 14 },
  { id: 'tm9',  name: 'James Taylor',    department: 'Engineering', role: 'Security Engineer',       currentLoad: 85, capacity: 40, assignedTasks: 9,  completedTasks: 13, skills: ['OWASP', 'Pen Testing', 'Compliance'],    availability: 6  },
  { id: 'tm10', name: 'Alex Martinez',   department: 'Design',      role: 'Frontend Developer',      currentLoad: 58, capacity: 40, assignedTasks: 6,  completedTasks: 10, skills: ['HTML/CSS', 'Accessibility', 'React'],    availability: 17 },
  { id: 'tm11', name: 'Sophie Anderson', department: 'Engineering', role: 'API Developer',           currentLoad: 71, capacity: 40, assignedTasks: 7,  completedTasks: 9,  skills: ['Node.js', 'GraphQL', 'Redis'],           availability: 12 },
  { id: 'tm12', name: 'Maria Garcia',    department: 'Operations',  role: 'Infrastructure Engineer', currentLoad: 76, capacity: 40, assignedTasks: 5,  completedTasks: 7,  skills: ['Kubernetes', 'Ansible', 'Linux'],        availability: 10 },
];

// ─── Task Dependencies ─────────────────────────────────────
export const mockDependencies: TaskDependency[] = [
  { id: 'd1',  fromTaskId: 't18', toTaskId: 't1',  type: 'blocks'     },
  { id: 'd2',  fromTaskId: 't1',  toTaskId: 't19', type: 'blocks'     },
  { id: 'd3',  fromTaskId: 't19', toTaskId: 't11', type: 'blocks'     },
  { id: 'd4',  fromTaskId: 't8',  toTaskId: 't2',  type: 'blocks'     },
  { id: 'd5',  fromTaskId: 't2',  toTaskId: 't5',  type: 'relates_to' },
  { id: 'd6',  fromTaskId: 't34', toTaskId: 't3',  type: 'relates_to' },
  { id: 'd7',  fromTaskId: 't3',  toTaskId: 't25', type: 'blocks'     },
  { id: 'd8',  fromTaskId: 't22', toTaskId: 't30', type: 'blocks'     },
  { id: 'd9',  fromTaskId: 't13', toTaskId: 't23', type: 'blocks'     },
  { id: 'd10', fromTaskId: 't4',  toTaskId: 't21', type: 'relates_to' },
  { id: 'd11', fromTaskId: 't24', toTaskId: 't13', type: 'relates_to' },
  { id: 'd12', fromTaskId: 't33', toTaskId: 't2',  type: 'blocks'     },
];

// ─── Skill Ratings ─────────────────────────────────────────
export const mockSkillRatings: SkillRating[] = [
  { memberId: 'tm1',  memberName: 'Sarah Chen',       skill: 'React/Frontend', rating: 2 },
  { memberId: 'tm1',  memberName: 'Sarah Chen',       skill: 'Backend/API',    rating: 1 },
  { memberId: 'tm1',  memberName: 'Sarah Chen',       skill: 'UI/UX Design',   rating: 5 },
  { memberId: 'tm1',  memberName: 'Sarah Chen',       skill: 'DevOps/Infra',   rating: 1 },
  { memberId: 'tm1',  memberName: 'Sarah Chen',       skill: 'Testing/QA',     rating: 3 },
  { memberId: 'tm1',  memberName: 'Sarah Chen',       skill: 'Project Mgmt',   rating: 5 },
  { memberId: 'tm1',  memberName: 'Sarah Chen',       skill: 'Data/Analytics', rating: 3 },
  { memberId: 'tm1',  memberName: 'Sarah Chen',       skill: 'Security',       rating: 1 },
  { memberId: 'tm2',  memberName: 'David Kim',        skill: 'React/Frontend', rating: 5 },
  { memberId: 'tm2',  memberName: 'David Kim',        skill: 'Backend/API',    rating: 4 },
  { memberId: 'tm2',  memberName: 'David Kim',        skill: 'UI/UX Design',   rating: 2 },
  { memberId: 'tm2',  memberName: 'David Kim',        skill: 'DevOps/Infra',   rating: 3 },
  { memberId: 'tm2',  memberName: 'David Kim',        skill: 'Testing/QA',     rating: 4 },
  { memberId: 'tm2',  memberName: 'David Kim',        skill: 'Project Mgmt',   rating: 2 },
  { memberId: 'tm2',  memberName: 'David Kim',        skill: 'Data/Analytics', rating: 4 },
  { memberId: 'tm2',  memberName: 'David Kim',        skill: 'Security',       rating: 3 },
  { memberId: 'tm3',  memberName: 'Emma Wilson',      skill: 'React/Frontend', rating: 3 },
  { memberId: 'tm3',  memberName: 'Emma Wilson',      skill: 'Backend/API',    rating: 0 },
  { memberId: 'tm3',  memberName: 'Emma Wilson',      skill: 'UI/UX Design',   rating: 5 },
  { memberId: 'tm3',  memberName: 'Emma Wilson',      skill: 'DevOps/Infra',   rating: 0 },
  { memberId: 'tm3',  memberName: 'Emma Wilson',      skill: 'Testing/QA',     rating: 2 },
  { memberId: 'tm3',  memberName: 'Emma Wilson',      skill: 'Project Mgmt',   rating: 3 },
  { memberId: 'tm3',  memberName: 'Emma Wilson',      skill: 'Data/Analytics', rating: 1 },
  { memberId: 'tm3',  memberName: 'Emma Wilson',      skill: 'Security',       rating: 0 },
  { memberId: 'tm4',  memberName: 'Michael Brown',    skill: 'React/Frontend', rating: 2 },
  { memberId: 'tm4',  memberName: 'Michael Brown',    skill: 'Backend/API',    rating: 5 },
  { memberId: 'tm4',  memberName: 'Michael Brown',    skill: 'UI/UX Design',   rating: 1 },
  { memberId: 'tm4',  memberName: 'Michael Brown',    skill: 'DevOps/Infra',   rating: 4 },
  { memberId: 'tm4',  memberName: 'Michael Brown',    skill: 'Testing/QA',     rating: 4 },
  { memberId: 'tm4',  memberName: 'Michael Brown',    skill: 'Project Mgmt',   rating: 2 },
  { memberId: 'tm4',  memberName: 'Michael Brown',    skill: 'Data/Analytics', rating: 3 },
  { memberId: 'tm4',  memberName: 'Michael Brown',    skill: 'Security',       rating: 3 },
  { memberId: 'tm5',  memberName: 'Lisa Wang',        skill: 'React/Frontend', rating: 4 },
  { memberId: 'tm5',  memberName: 'Lisa Wang',        skill: 'Backend/API',    rating: 4 },
  { memberId: 'tm5',  memberName: 'Lisa Wang',        skill: 'UI/UX Design',   rating: 2 },
  { memberId: 'tm5',  memberName: 'Lisa Wang',        skill: 'DevOps/Infra',   rating: 2 },
  { memberId: 'tm5',  memberName: 'Lisa Wang',        skill: 'Testing/QA',     rating: 3 },
  { memberId: 'tm5',  memberName: 'Lisa Wang',        skill: 'Project Mgmt',   rating: 2 },
  { memberId: 'tm5',  memberName: 'Lisa Wang',        skill: 'Data/Analytics', rating: 3 },
  { memberId: 'tm5',  memberName: 'Lisa Wang',        skill: 'Security',       rating: 4 },
  { memberId: 'tm6',  memberName: 'Chris Johnson',    skill: 'React/Frontend', rating: 1 },
  { memberId: 'tm6',  memberName: 'Chris Johnson',    skill: 'Backend/API',    rating: 3 },
  { memberId: 'tm6',  memberName: 'Chris Johnson',    skill: 'UI/UX Design',   rating: 0 },
  { memberId: 'tm6',  memberName: 'Chris Johnson',    skill: 'DevOps/Infra',   rating: 5 },
  { memberId: 'tm6',  memberName: 'Chris Johnson',    skill: 'Testing/QA',     rating: 3 },
  { memberId: 'tm6',  memberName: 'Chris Johnson',    skill: 'Project Mgmt',   rating: 3 },
  { memberId: 'tm6',  memberName: 'Chris Johnson',    skill: 'Data/Analytics', rating: 2 },
  { memberId: 'tm6',  memberName: 'Chris Johnson',    skill: 'Security',       rating: 4 },
  { memberId: 'tm7',  memberName: 'Mike Johnson',     skill: 'React/Frontend', rating: 5 },
  { memberId: 'tm7',  memberName: 'Mike Johnson',     skill: 'Backend/API',    rating: 3 },
  { memberId: 'tm7',  memberName: 'Mike Johnson',     skill: 'UI/UX Design',   rating: 3 },
  { memberId: 'tm7',  memberName: 'Mike Johnson',     skill: 'DevOps/Infra',   rating: 3 },
  { memberId: 'tm7',  memberName: 'Mike Johnson',     skill: 'Testing/QA',     rating: 4 },
  { memberId: 'tm7',  memberName: 'Mike Johnson',     skill: 'Project Mgmt',   rating: 2 },
  { memberId: 'tm7',  memberName: 'Mike Johnson',     skill: 'Data/Analytics', rating: 1 },
  { memberId: 'tm7',  memberName: 'Mike Johnson',     skill: 'Security',       rating: 2 },
  { memberId: 'tm8',  memberName: 'Emily Rodriguez',  skill: 'React/Frontend', rating: 2 },
  { memberId: 'tm8',  memberName: 'Emily Rodriguez',  skill: 'Backend/API',    rating: 0 },
  { memberId: 'tm8',  memberName: 'Emily Rodriguez',  skill: 'UI/UX Design',   rating: 5 },
  { memberId: 'tm8',  memberName: 'Emily Rodriguez',  skill: 'DevOps/Infra',   rating: 0 },
  { memberId: 'tm8',  memberName: 'Emily Rodriguez',  skill: 'Testing/QA',     rating: 2 },
  { memberId: 'tm8',  memberName: 'Emily Rodriguez',  skill: 'Project Mgmt',   rating: 1 },
  { memberId: 'tm8',  memberName: 'Emily Rodriguez',  skill: 'Data/Analytics', rating: 1 },
  { memberId: 'tm8',  memberName: 'Emily Rodriguez',  skill: 'Security',       rating: 0 },
  { memberId: 'tm9',  memberName: 'James Taylor',     skill: 'React/Frontend', rating: 2 },
  { memberId: 'tm9',  memberName: 'James Taylor',     skill: 'Backend/API',    rating: 4 },
  { memberId: 'tm9',  memberName: 'James Taylor',     skill: 'UI/UX Design',   rating: 0 },
  { memberId: 'tm9',  memberName: 'James Taylor',     skill: 'DevOps/Infra',   rating: 3 },
  { memberId: 'tm9',  memberName: 'James Taylor',     skill: 'Testing/QA',     rating: 5 },
  { memberId: 'tm9',  memberName: 'James Taylor',     skill: 'Project Mgmt',   rating: 2 },
  { memberId: 'tm9',  memberName: 'James Taylor',     skill: 'Data/Analytics', rating: 2 },
  { memberId: 'tm9',  memberName: 'James Taylor',     skill: 'Security',       rating: 5 },
  { memberId: 'tm10', memberName: 'Alex Martinez',    skill: 'React/Frontend', rating: 4 },
  { memberId: 'tm10', memberName: 'Alex Martinez',    skill: 'Backend/API',    rating: 2 },
  { memberId: 'tm10', memberName: 'Alex Martinez',    skill: 'UI/UX Design',   rating: 3 },
  { memberId: 'tm10', memberName: 'Alex Martinez',    skill: 'DevOps/Infra',   rating: 2 },
  { memberId: 'tm10', memberName: 'Alex Martinez',    skill: 'Testing/QA',     rating: 3 },
  { memberId: 'tm10', memberName: 'Alex Martinez',    skill: 'Project Mgmt',   rating: 2 },
  { memberId: 'tm10', memberName: 'Alex Martinez',    skill: 'Data/Analytics', rating: 2 },
  { memberId: 'tm10', memberName: 'Alex Martinez',    skill: 'Security',       rating: 1 },
  { memberId: 'tm11', memberName: 'Sophie Anderson',  skill: 'React/Frontend', rating: 3 },
  { memberId: 'tm11', memberName: 'Sophie Anderson',  skill: 'Backend/API',    rating: 5 },
  { memberId: 'tm11', memberName: 'Sophie Anderson',  skill: 'UI/UX Design',   rating: 1 },
  { memberId: 'tm11', memberName: 'Sophie Anderson',  skill: 'DevOps/Infra',   rating: 3 },
  { memberId: 'tm11', memberName: 'Sophie Anderson',  skill: 'Testing/QA',     rating: 3 },
  { memberId: 'tm11', memberName: 'Sophie Anderson',  skill: 'Project Mgmt',   rating: 2 },
  { memberId: 'tm11', memberName: 'Sophie Anderson',  skill: 'Data/Analytics', rating: 3 },
  { memberId: 'tm11', memberName: 'Sophie Anderson',  skill: 'Security',       rating: 4 },
  { memberId: 'tm12', memberName: 'Maria Garcia',     skill: 'React/Frontend', rating: 1 },
  { memberId: 'tm12', memberName: 'Maria Garcia',     skill: 'Backend/API',    rating: 2 },
  { memberId: 'tm12', memberName: 'Maria Garcia',     skill: 'UI/UX Design',   rating: 0 },
  { memberId: 'tm12', memberName: 'Maria Garcia',     skill: 'DevOps/Infra',   rating: 5 },
  { memberId: 'tm12', memberName: 'Maria Garcia',     skill: 'Testing/QA',     rating: 3 },
  { memberId: 'tm12', memberName: 'Maria Garcia',     skill: 'Project Mgmt',   rating: 2 },
  { memberId: 'tm12', memberName: 'Maria Garcia',     skill: 'Data/Analytics', rating: 2 },
  { memberId: 'tm12', memberName: 'Maria Garcia',     skill: 'Security',       rating: 3 },
];

// ─── Email Threads ─────────────────────────────────────────
export const mockEmails: EmailThread[] = [
  {
    id: 'e1', from: 'Sarah Chen', fromEmail: 'sarah.chen@techcorp.com',
    subject: 'Re: Mobile App Redesign — Sprint 4 UX Review',
    preview: 'Great progress this sprint! I\'ve reviewed the authentication flow designs and have a few feedback points. The biometric auth looks clean but we need to consider the error state for when Face ID fails. Also, the onboarding screens are looking fantastic — please make sure the progress indicator is accessible for screen readers.',
    date: '2026-02-17T09:23:00', unread: true, starred: true,
    tags: ['Sprint Review', 'Design'], replies: 3,
    projectId: 'p1', projectName: 'Mobile App Redesign',
    folder: 'inbox',
  },
  {
    id: 'e2', from: 'RetailCo PM', fromEmail: 'james.richardson@retailco.com',
    subject: '[URGENT] E-commerce Platform — Stripe Payment Failures in Staging',
    preview: 'We\'re experiencing critical issues with the Stripe integration in staging. Transactions above $500 are consistently failing with error code 402 (payment_intent_authentication_failure). This is completely blocking our UAT session scheduled for tomorrow. Can we get on a call in the next hour? Our finance team is watching this closely as the go-live date is in 2 weeks.',
    date: '2026-02-17T08:45:00', unread: true, starred: false,
    tags: ['Urgent', 'Bug', 'Client'], attachments: 2, replies: 1,
    projectId: 'p2', projectName: 'E-commerce Platform',
    folder: 'inbox', taskId: 't8',
  },
  {
    id: 'e3', from: 'Michael Brown', fromEmail: 'michael.brown@internal.com',
    subject: 'Platform API v3 — GraphQL Schema v0.3 Ready for Review',
    preview: 'Attached is the proposed schema design for the GraphQL layer. I\'ve incorporated all the feedback from last week\'s architecture review. Key changes in v0.3: Added cursor-based pagination on all list resolvers, separated mutation inputs from query types, added @deprecated directives on v2 fields, and added field-level authorization directives. Sophie and I will walk through it in tomorrow\'s tech review. Please add comments in the Figma/Notion doc.',
    date: '2026-02-16T16:30:00', unread: false, starred: false,
    tags: ['API', 'Review'], attachments: 1, replies: 2,
    projectId: 'p4', projectName: 'Platform API v3',
    folder: 'inbox',
  },
  {
    id: 'e4', from: 'StartupXYZ CEO', fromEmail: 'ceo@startupxyz.io',
    subject: 'Website Redesign — Brand Color System Approved ✅',
    preview: 'Love the new brand color system Emma presented during yesterday\'s call. The teal accent (#0D9488) works really well against the primary navy and the warm cream background is much more approachable than the old stark white. We\'re ready to proceed to the full wireframe stage. One request: can you also prepare a dark mode version of the palette? Our users have been asking for it. Please share the Figma link and revised timeline.',
    date: '2026-02-16T14:15:00', unread: false, starred: true,
    tags: ['Approval', 'Client'], replies: 1,
    projectId: 'p3', projectName: 'Website Redesign',
    folder: 'inbox',
  },
  {
    id: 'e5', from: 'Chris Johnson', fromEmail: 'chris.j@internal.com',
    subject: 'Backend Infra — Kubernetes Cluster Phase 1 Complete 🚀',
    preview: 'Great news! Phase 1 of the Kubernetes migration is complete. All 8 legacy microservices are now running in the new GKE cluster. P99 latency improved by 23% and memory usage is down 31% thanks to proper resource limits. Grafana dashboards are up and showing green across all services. Phase 2 starts next week — migrating the database layer. I\'ll need Maria\'s help with the Postgres operator configuration.',
    date: '2026-02-15T11:00:00', unread: false, starred: false,
    tags: ['Infrastructure', 'Update'], replies: 4,
    projectId: 'p5', projectName: 'Backend Infrastructure',
    folder: 'inbox',
  },
  {
    id: 'e6', from: 'TechCorp Inc — PM Team', fromEmail: 'pm@techcorp.com',
    subject: 'Weekly Status Report Required — Week 7 (Due Friday)',
    preview: 'Hi team, as per our contract agreement (Clause 8.2), please submit the weekly status report by Friday Feb 20 at 5pm EST. Required sections: (1) Tasks completed this week with hours logged, (2) Tasks planned for next week, (3) Blockers and risks with mitigation, (4) Budget burn rate vs plan. Please use the template in the shared Drive folder. Missing 2 weeks of reports will trigger a contract review clause.',
    date: '2026-02-14T09:00:00', unread: true, starred: false,
    tags: ['Report', 'Client', 'Action Required'],
    projectId: 'p1', projectName: 'Mobile App Redesign',
    folder: 'inbox',
  },
  {
    id: 'e7', from: 'Emma Wilson', fromEmail: 'emma.wilson@internal.com',
    subject: 'Website Redesign — Component Library Ready for Dev Handoff 🎨',
    preview: 'The complete component library is now live in Figma and ready for developer handoff. 84 components across 12 categories — buttons, forms, navigation, cards, modals, tables, charts, notifications, typography, icons, layout, and utilities. Every component has: responsive variants, hover/focus/active states, accessibility annotations (ARIA labels, roles, contrast ratios), usage guidelines, and do\'s and don\'ts. The Storybook link is in the Figma file description.',
    date: '2026-02-14T15:45:00', unread: false, starred: false,
    tags: ['Design Handoff'], attachments: 1, replies: 3,
    projectId: 'p3', projectName: 'Website Redesign',
    folder: 'inbox',
  },
  {
    id: 'e8', from: 'James Taylor', fromEmail: 'james.taylor@internal.com',
    subject: 'E-commerce Security Audit — Critical Findings Requiring Immediate Action',
    preview: 'The Phase 1 penetration test is complete. We found 3 critical vulnerabilities that must be patched before go-live: (1) SQL injection in the product search endpoint — a malicious query can dump the entire users table, (2) Payment webhook endpoint accepts events without signature verification allowing replay attacks, (3) Admin panel accessible without MFA. I\'ve linked the findings to tasks ECP-BUG-001 and ECP-BUG-012. Full report is attached.',
    date: '2026-02-16T17:15:00', unread: true, starred: true,
    tags: ['Security', 'Critical', 'Action Required'], attachments: 1, replies: 0,
    projectId: 'p2', projectName: 'E-commerce Platform',
    folder: 'inbox', taskId: 't4',
  },
  {
    id: 'e9', from: 'Sophie Anderson', fromEmail: 'sophie.anderson@internal.com',
    subject: 'Platform API v3 — JWT Refresh Token Implementation Complete',
    preview: 'JWT refresh token implementation is done. I\'ve implemented: sliding window refresh with 30-day max lifetime, token rotation on every refresh (old token immediately blacklisted in Redis), family-level revocation for compromised refresh tokens, rate limiting on the refresh endpoint (5 req/min per IP), and audit logging for all auth events. One concern: the token blacklist Redis set will grow unbounded — we need a TTL strategy. Can we discuss in tomorrow\'s standup?',
    date: '2026-02-15T13:45:00', unread: false, starred: false,
    tags: ['Security', 'API', 'Update'], replies: 2,
    projectId: 'p4', projectName: 'Platform API v3',
    folder: 'inbox',
  },
  {
    id: 'e10', from: 'David Kim', fromEmail: 'david.kim@internal.com',
    subject: 'E-commerce Platform — Database Migration Script Completed',
    preview: 'Database migration script is ready for production. All 47 tables are migrated with proper foreign key constraints, indexes, and triggers. I\'ve also added rollback scripts. Data validation tests show 100% data integrity across all tables. We should schedule the production migration for this weekend during the maintenance window.',
    date: '2026-02-13T10:30:00', unread: false, starred: false,
    tags: ['Database', 'Migration'], replies: 1,
    projectId: 'p2', projectName: 'E-commerce Platform',
    folder: 'archived',
  },
  {
    id: 'e11', from: 'Lisa Wang', fromEmail: 'lisa.wang@internal.com',
    subject: 'E-commerce - Payment Flow Testing Complete ✅',
    preview: 'All payment flow tests are passing. Tested with Visa, Mastercard, AmEx, and PayPal. Edge cases covered: declined cards, insufficient funds, network timeouts, and webhook retries. Ready for UAT.',
    date: '2026-02-12T16:00:00', unread: false, starred: false,
    tags: ['Testing', 'Payment'], replies: 0,
    projectId: 'p2', projectName: 'E-commerce Platform',
    folder: 'archived',
  },
  {
    id: 'e12', from: 'Mike Johnson', fromEmail: 'mike.johnson@internal.com',
    subject: 'Mobile App - Dark Mode Implementation',
    preview: 'Dark mode is now implemented across all screens. Used system color tokens and tested on both iOS and Android. Looks great and respects user system preferences.',
    date: '2026-02-11T14:20:00', unread: false, starred: false,
    tags: ['Feature', 'Mobile'], replies: 2,
    projectId: 'p1', projectName: 'Mobile App Redesign',
    folder: 'archived',
  },
];
