// WORK Module Mock Data - v1.3
import { Project, Milestone, Task, TeamMember } from './types';

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Mobile App Redesign',
    client: 'TechCorp Inc',
    department: 'Product',
    status: 'Active',
    priority: 'High',
    startDate: '2024-12-01',
    endDate: '2025-03-15',
    progress: 45,
    budget: 120000,
    spent: 54000,
    burnRate: 85,
    profitRisk: 'Low',
    team: ['Sarah Chen', 'Mike Johnson', 'Emily Rodriguez'],
    teamLead: 'Sarah Chen',
    description: 'Complete redesign of mobile application with new UX patterns'
  },
  {
    id: '2',
    name: 'E-commerce Platform',
    client: 'RetailCo',
    department: 'Engineering',
    status: 'At Risk',
    priority: 'High',
    startDate: '2024-11-15',
    endDate: '2025-02-28',
    progress: 38,
    budget: 200000,
    spent: 140000,
    burnRate: 120,
    profitRisk: 'High',
    team: ['David Kim', 'Lisa Wang', 'James Taylor'],
    teamLead: 'David Kim',
    description: 'Full-stack e-commerce platform with payment integration'
  },
  {
    id: '3',
    name: 'Website Redesign',
    client: 'StartupXYZ',
    department: 'Design',
    status: 'Active',
    priority: 'Medium',
    startDate: '2025-01-05',
    endDate: '2025-04-20',
    progress: 22,
    budget: 75000,
    spent: 16500,
    burnRate: 65,
    profitRisk: 'Low',
    team: ['Emma Wilson', 'Alex Martinez'],
    teamLead: 'Emma Wilson',
    description: 'Modern website redesign with improved accessibility'
  },
  {
    id: '4',
    name: 'Platform API',
    client: 'Internal',
    department: 'Engineering',
    status: 'Active',
    priority: 'Medium',
    startDate: '2024-12-10',
    endDate: '2025-05-30',
    progress: 56,
    budget: 150000,
    spent: 84000,
    burnRate: 75,
    profitRisk: 'Medium',
    team: ['Michael Brown', 'Sophie Anderson'],
    teamLead: 'Michael Brown',
    description: 'RESTful API for platform integration'
  },
  {
    id: '5',
    name: 'Backend Infrastructure',
    client: 'Internal',
    department: 'Operations',
    status: 'Active',
    priority: 'Low',
    startDate: '2024-11-01',
    endDate: '2025-06-15',
    progress: 67,
    budget: 100000,
    spent: 67000,
    burnRate: 70,
    profitRisk: 'None',
    team: ['Chris Johnson', 'Maria Garcia'],
    teamLead: 'Chris Johnson',
    description: 'Infrastructure modernization and optimization'
  }
];

export const mockMilestones: Milestone[] = [
  {
    id: 'm1',
    projectId: '1',
    projectName: 'Mobile App Redesign',
    name: 'Phase 1: Discovery & Research',
    owner: 'Sarah Chen',
    startDate: '2024-12-01',
    endDate: '2024-12-20',
    progress: 100,
    status: 'Completed',
    taskCount: 8,
    completedTasks: 8
  },
  {
    id: 'm2',
    projectId: '1',
    projectName: 'Mobile App Redesign',
    name: 'Phase 2: Design System',
    owner: 'Sarah Chen',
    startDate: '2024-12-21',
    endDate: '2025-01-15',
    progress: 75,
    status: 'In Progress',
    taskCount: 12,
    completedTasks: 9
  },
  {
    id: 'm3',
    projectId: '1',
    projectName: 'Mobile App Redesign',
    name: 'Phase 3: Development',
    owner: 'Mike Johnson',
    startDate: '2025-01-16',
    endDate: '2025-02-28',
    progress: 20,
    status: 'In Progress',
    taskCount: 24,
    completedTasks: 5
  },
  {
    id: 'm4',
    projectId: '2',
    projectName: 'E-commerce Platform',
    name: 'Backend Architecture',
    owner: 'David Kim',
    startDate: '2024-11-15',
    endDate: '2024-12-31',
    progress: 100,
    status: 'Completed',
    taskCount: 15,
    completedTasks: 15
  },
  {
    id: 'm5',
    projectId: '2',
    projectName: 'E-commerce Platform',
    name: 'Payment Integration',
    owner: 'Lisa Wang',
    startDate: '2025-01-01',
    endDate: '2025-01-25',
    progress: 45,
    status: 'Overdue',
    taskCount: 10,
    completedTasks: 5
  },
  {
    id: 'm6',
    projectId: '3',
    projectName: 'Website Redesign',
    name: 'Visual Design',
    owner: 'Emma Wilson',
    startDate: '2025-01-05',
    endDate: '2025-02-10',
    progress: 35,
    status: 'In Progress',
    taskCount: 14,
    completedTasks: 5
  },
  {
    id: 'm7',
    projectId: '4',
    projectName: 'Platform API',
    name: 'Core Endpoints',
    owner: 'Michael Brown',
    startDate: '2024-12-10',
    endDate: '2025-02-15',
    progress: 80,
    status: 'In Progress',
    taskCount: 20,
    completedTasks: 16
  }
];

export const mockTasks: Task[] = [
  {
    id: '1',
    taskId: 'T-001',
    title: 'Design user authentication flow',
    projectId: '1',
    projectName: 'Mobile App Redesign',
    milestoneId: 'm2',
    milestoneName: 'Phase 2: Design System',
    assignee: 'Sarah Chen',
    assigneeDepartment: 'Product',
    status: 'In Progress',
    approvalStatus: 'Approved',
    priority: 'High',
    startDate: '2025-01-02',
    dueDate: '2025-01-05',
    estimate: '8h',
    actualTime: '5h 30m',
    billable: true,
    hasEvidence: true,
    evidenceCount: 3,
    burnAmount: 550,
    profitImpact: 200
  },
  {
    id: '2',
    taskId: 'T-002',
    title: 'Implement payment gateway',
    projectId: '2',
    projectName: 'E-commerce Platform',
    milestoneId: 'm5',
    milestoneName: 'Payment Integration',
    assignee: 'Lisa Wang',
    assigneeDepartment: 'Engineering',
    status: 'In Progress',
    approvalStatus: 'Approved',
    priority: 'High',
    startDate: '2025-01-10',
    dueDate: '2025-01-02',
    estimate: '16h',
    actualTime: '18h 15m',
    billable: true,
    hasEvidence: false,
    evidenceCount: 0,
    burnAmount: 1825,
    profitImpact: -200
  },
  {
    id: '3',
    taskId: 'T-003',
    title: 'Update API documentation',
    projectId: '4',
    projectName: 'Platform API',
    milestoneId: 'm7',
    milestoneName: 'Core Endpoints',
    assignee: 'Michael Brown',
    assigneeDepartment: 'Engineering',
    status: 'To Do',
    approvalStatus: 'Approved',
    priority: 'Medium',
    dueDate: '2025-01-08',
    estimate: '4h',
    actualTime: '0h',
    billable: false,
    hasEvidence: false,
    evidenceCount: 0
  },
  {
    id: '4',
    taskId: 'T-004',
    title: 'Create landing page mockups',
    projectId: '3',
    projectName: 'Website Redesign',
    milestoneId: 'm6',
    milestoneName: 'Visual Design',
    assignee: 'Emma Wilson',
    assigneeDepartment: 'Design',
    status: 'Done',
    approvalStatus: 'Approved',
    priority: 'High',
    startDate: '2025-01-06',
    dueDate: '2025-01-12',
    estimate: '12h',
    actualTime: '11h 30m',
    billable: true,
    hasEvidence: true,
    evidenceCount: 8,
    burnAmount: 1150,
    profitImpact: 100
  },
  {
    id: '5',
    taskId: 'T-005',
    title: 'Fix checkout flow bug',
    projectId: '2',
    projectName: 'E-commerce Platform',
    milestoneId: 'm5',
    milestoneName: 'Payment Integration',
    assignee: 'David Kim',
    assigneeDepartment: 'Engineering',
    status: 'To Do',
    approvalStatus: 'Approved',
    priority: 'High',
    dueDate: '2024-12-30',
    estimate: '6h',
    actualTime: '0h',
    billable: true,
    hasEvidence: false,
    evidenceCount: 0
  },
  {
    id: '6',
    taskId: 'T-006',
    title: 'Database optimization',
    projectId: '5',
    projectName: 'Backend Infrastructure',
    assignee: 'Chris Johnson',
    assigneeDepartment: 'Operations',
    status: 'Done',
    approvalStatus: 'Approved',
    priority: 'Low',
    startDate: '2024-12-15',
    dueDate: '2024-12-28',
    estimate: '4h',
    actualTime: '4h 45m',
    billable: false,
    hasEvidence: true,
    evidenceCount: 2,
    burnAmount: 475
  },
  {
    id: '7',
    taskId: 'T-007',
    title: 'Setup CI/CD pipeline',
    projectId: '1',
    projectName: 'Mobile App Redesign',
    milestoneId: 'm3',
    milestoneName: 'Phase 3: Development',
    assignee: 'Mike Johnson',
    assigneeDepartment: 'Product',
    status: 'Pending Approval',
    approvalStatus: 'Pending Approval',
    priority: 'Medium',
    dueDate: '2025-01-20',
    estimate: '8h',
    actualTime: '0h',
    billable: false,
    hasEvidence: false,
    evidenceCount: 0,
    submittedByEmployee: true,
    submittedBy: 'Mike Johnson',
    description: 'Need to setup automated deployment pipeline'
  },
  {
    id: '8',
    taskId: 'T-008',
    title: 'Security audit review',
    projectId: '2',
    projectName: 'E-commerce Platform',
    milestoneId: 'm5',
    milestoneName: 'Payment Integration',
    assignee: 'James Taylor',
    assigneeDepartment: 'Engineering',
    status: 'In Progress',
    approvalStatus: 'Approved',
    priority: 'High',
    startDate: '2025-01-15',
    dueDate: '2025-01-18',
    estimate: '10h',
    actualTime: '6h',
    billable: true,
    hasEvidence: true,
    evidenceCount: 5,
    burnAmount: 600,
    profitImpact: 150
  },
  {
    id: '9',
    taskId: 'T-009',
    title: 'Mobile responsive testing',
    projectId: '3',
    projectName: 'Website Redesign',
    milestoneId: 'm6',
    milestoneName: 'Visual Design',
    assignee: 'Alex Martinez',
    assigneeDepartment: 'Design',
    status: 'To Do',
    approvalStatus: 'Approved',
    priority: 'Medium',
    dueDate: '2025-01-25',
    estimate: '6h',
    actualTime: '0h',
    billable: true,
    hasEvidence: false,
    evidenceCount: 0
  },
  {
    id: '10',
    taskId: 'T-010',
    title: 'Performance optimization',
    projectId: '4',
    projectName: 'Platform API',
    milestoneId: 'm7',
    milestoneName: 'Core Endpoints',
    assignee: 'Sophie Anderson',
    assigneeDepartment: 'Engineering',
    status: 'Rejected',
    approvalStatus: 'Rejected',
    priority: 'Low',
    dueDate: '2025-02-10',
    estimate: '5h',
    actualTime: '0h',
    billable: false,
    hasEvidence: false,
    evidenceCount: 0,
    submittedByEmployee: true,
    submittedBy: 'Sophie Anderson',
    description: 'Rejected - not aligned with current sprint goals'
  }
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    department: 'Product',
    role: 'Product Manager',
    currentLoad: 85,
    capacity: 40,
    assignedTasks: 8,
    completedTasks: 12
  },
  {
    id: '2',
    name: 'David Kim',
    department: 'Engineering',
    role: 'Senior Developer',
    currentLoad: 95,
    capacity: 40,
    assignedTasks: 12,
    completedTasks: 18
  },
  {
    id: '3',
    name: 'Emma Wilson',
    department: 'Design',
    role: 'Lead Designer',
    currentLoad: 70,
    capacity: 40,
    assignedTasks: 6,
    completedTasks: 9
  },
  {
    id: '4',
    name: 'Michael Brown',
    department: 'Engineering',
    role: 'Backend Developer',
    currentLoad: 78,
    capacity: 40,
    assignedTasks: 10,
    completedTasks: 15
  },
  {
    id: '5',
    name: 'Lisa Wang',
    department: 'Engineering',
    role: 'Full Stack Developer',
    currentLoad: 92,
    capacity: 40,
    assignedTasks: 11,
    completedTasks: 14
  },
  {
    id: '6',
    name: 'Chris Johnson',
    department: 'Operations',
    role: 'DevOps Engineer',
    currentLoad: 65,
    capacity: 40,
    assignedTasks: 5,
    completedTasks: 20
  }
];
